Backend docs
sandboxnu/nucarpool pull request #7
Opened 2022-10-16 19:03 UTC by lukejianu

CLOSES #2. Added documentation to the db folder.

2022-10-16 19:14 UTC, dillydally414 reviewed
Some minor issues

2022-10-16 19:14 UTC, dillydally414 commented on prisma/schema.prisma
> +// the Prisma Clienet is generated.
```suggestion
// the Prisma Client is generated.
```

2022-10-16 19:14 UTC, dillydally414 commented on prisma/schema.prisma
> +// Represents a Role.
What is a role?

2022-10-16 19:38 UTC, DavidOB1 approved these changes
Looks pretty epic

2022-10-16 19:38 UTC, DavidOB1 commented on prisma/schema.prisma
> +// Represents a User--need this for NextAuth and obviously the data it stores.
Sounds a bit sassy.
```suggestion
// Represents a User--need this for NextAuth and the data it stores.
```

2022-10-16 19:38 UTC, DavidOB1 commented on src/server/db/README.md
> +### Contents:
```suggestion
### Contents
```

2022-10-16 20:17 UTC, ispapa approved these changes
Minor typos

2022-10-16 20:17 UTC, ispapa commented on src/server/db/README.md
> +2. When edit is called, The input must first pass through the ```z.object```, which enforces type and other constraints on the data. The key part here is if you want to do scheme validation, follow t
```suggestion
2. When edit is called, the input must first pass through the ```z.object```, which enforces type and other constraints on the data. The key part here is if you want to do schema validation, follow the syntax below, specifying what you want as a ```z.object```, and putting it as the ```input```. tRPC supports Zod, which is why we can pass it to ```input``` as shown below.
```

2022-10-17 01:08 UTC, dillydally414 requested changes
Going to be a contrarian and request changes, not specifically for my review but for all of them. @ispapa @DavidOB1 don't be afraid to request changes or be a little brutal, PRs are your time to tear into each other's work in a "professional" manner - it's how we as a team improve :party-blob:

2022-10-17 01:08 UTC, dillydally414 commented on src/server/db/README.md
> +If you change something in the schema.prisma file, the change must be reflected in your actual database and prisma has to regenerate the code for the client. You can achieve both of these with a ```y
```suggestion
If you change something in the schema.prisma file, the change must be reflected in your actual database and prisma has to regenerate the code for the client. You can achieve both of these with a ```yarn db:schema``` command. This syncs everything back up.
```

2022-10-17 01:08 UTC, dillydally414 commented on src/server/db/README.md
> +[Zod](https://github.com/colinhacks/zod) is used to validate calls to our tRPC routes/endpoints.
```suggestion
[Zod](https://zod.dev/) is used to validate input object types in calls to our tRPC routes/endpoints. 
```

2022-10-17 23:09 UTC, lukejianu reviewed
testing where this goes.

2022-10-18 00:33 UTC, dillydally414 submitted a review, later dismissed

2022-10-18 00:45 UTC, devashish9 approved these changes
smh

2022-10-18 00:48 UTC, dillydally414 approved these changes
😒 dismissing my stale review.......

2022-10-18 01:47 UTC, merged