Auth pages
sandboxnu/nucarpool pull request #9
Opened 2022-10-16 19:58 UTC by ispapa

Closes #3 . Abstracts page validation.

2022-10-17 01:16 UTC, dillydally414 requested changes
The meat of this PR is good, just some small fixes requested :)

2022-10-17 01:16 UTC, dillydally414 commented on src/pages/index.tsx
> +export default () => ProtectedPage(Home);
Can we add a comment here explaining why this arrow notation is necessary?

2022-10-17 01:16 UTC, dillydally414 commented on src/utils/auth.tsx
> +/**
Actually I take back the other comment, maybe we should add something in the JSDoc here for reference in future pages (so we know the arrow notation is necessary)? At least one or the other should be added though.

2022-10-17 01:16 UTC, dillydally414 commented on src/pages/onboard.tsx
>  import { Combobox, Transition } from "@headlessui/react";
We should protect this page

2022-10-17 01:16 UTC, dillydally414 commented on src/pages/settings.tsx
>  import { Combobox, Transition } from "@headlessui/react";
We should also protect this page

2022-10-18 00:47 UTC, lukejianu approved these changes
Looks good to me.

2022-10-23 17:27 UTC, dillydally414 approved these changes

2022-10-23 17:36 UTC, devashish9 approved these changes
Everything looks good, I'd be down to go through the exact changes that were needed to make the abstract validation work. Isabelle, you can merge this branch in during GM!

2022-10-23 18:24 UTC, merged